# fly.toml file generated for tidyurl on 2023-04-12T16:36:19+07:00

app = "tidyurl"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sin"
processes = []

[env]
  PORT = ":8080"
  VITE_API_ENDPOINT = "https://tidyurl.fly.dev"
  BASE_URL = "https://tidyurl.fly.dev"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
